INSERT INTO stop (Id, stopName, previousStop, nextStop)
VALUES
(1, 'La Défense', NULL, 'Esplanade de La Défense'),
(2, 'Esplanade de La Défense', 'La Défense', 'Pont de Neuilly'),
(3, 'Pont de Neuilly', 'Esplanade de La Défense', 'Les Sablons'),
(4, 'Les Sablons', 'Pont de Neuilly', 'Porte Maillot'),
(5, 'Porte Maillot', 'Les Sablons', 'Argentine'),
(6, 'Argentine', 'Porte Maillot', 'Charles de Gaulle Étoile'),
(7, 'Charles de Gaulle Étoile', 'Argentine', 'George V'),
(8, 'George V', 'Charles de Gaulle Étoile', 'Franklin D. Roosevelt'),
(9, 'Franklin D. Roosevelt', 'George V', 'Champs-Élysées Clemenceau'),
(10, 'Champs-Élysées Clemenceau', 'Franklin D. Roosevelt', 'Concorde'),
(11, 'Concorde', 'Champs-Élysées Clemenceau', 'Tuileries'),
(12, 'Tuileries', 'Concorde', 'Palais Royal Musée du Louvre'),
(13, 'Palais Royal Musée du Louvre', 'Tuileries', 'Louvre Rivoli'),
(14, 'Louvre Rivoli', 'Palais Royal Musée du Louvre', 'Châtelet'),
(15, 'Châtelet', 'Louvre Rivoli', 'Hôtel de Ville'),
(16, 'Hôtel de Ville', 'Châtelet', 'Saint-Paul'),
(17, 'Saint-Paul', 'Hôtel de Ville', 'Bastille'),
(18, 'Bastille', 'Saint-Paul', 'Gare de Lyon'),
(19, 'Gare de Lyon', 'Bastille', 'Reuilly Diderot'),
(20, 'Reuilly Diderot', 'Gare de Lyon', 'Nation'),
(21, 'Nation', 'Reuilly Diderot', 'Porte de Vincennes'),
(22, 'Porte de Vincennes', 'Nation', 'Saint-Mandé'),
(23, 'Saint-Mandé', 'Porte de Vincennes', 'Bérault'),
(24, 'Bérault', 'Saint-Mandé', 'Château de Vincennes'),
(25, 'Château de Vincennes', 'Bérault', NULL);
